movies = [
    'The Shawshank Redemption',
    'The Godfather',
    'The Dark Knight',
    'Pulp Fiction',
    'The Lord of the Rings: The Return of the King',
    'Forrest Gump',
    'Inception',
    'Fight Club',
    'The Lord of the Rings: The Fellowship of the Ring',
    'The Matrix',
    'Goodfellas',
    'The Empire Strikes Back', 
    'The Lord of the Rings: The Two Towers', 
    'Interstellar', 
    'The Usual Suspects',
    'Schindler\'s List', 
    'The Departed', 'Gladiator', 
    'The Silence of the Lambs', 
    'Se7en',
    'The Green Mile', 
    'Léon: The Professional', 
    'The Lion King', 
    'Casablanca', 
    'City of God',
    'Spirited Away', 
    'Saving Private Ryan', 
    'Once Upon a Time in the West', 
    'The Intouchables', 
    'The Prestige',
    'Whiplash', 
    'The Great Dictator', 
    'Psycho', 
    'The Shining', 
    'Memento',
    'The Seventh Seal', 
    'Parasite', 
    'Cinema Paradiso', 
    'Back to the Future', 
    'Pulp Fiction',
    'The Grand Budapest Hotel', 
    'Jaws', 
    'The Big Lebowski', 
    'A Clockwork Orange', 
    'Reservoir Dogs',
    'Gone with the Wind', 
    'Lawrence of Arabia', 
    'The Wizard of Oz', 
    'Blade Runner', 
    'The Terminator',
    'The Social Network', 
    '12 Angry Men', 
    'The Big Short', 
    'Birdman', 
    'The Revenant',
    'No Country for Old Men', 
    'A Beautiful Mind', 
    'The Exorcist', 
    'The Hunt for Red October', 
    'Django Unchained',
    'Amélie', 
    'The Silence of the Lambs', 
    'The Princess Bride', 
    'The Wolf of Wall Street', 
    'Her',
    'Inglourious Basterds', 
    'The Departed', 
    'Moulin Rouge!', 
    'Joker', 
    'Black Swan',
    'The Imitation Game', 
    'The Theory of Everything', 
    'Spotlight', 
    'Arrival', 
    'Get Out',
    'Baby Driver', 
    'Mad Max: Fury Road', 
    'La La Land', 
    'The Favourite', 
    'The Shape of Water',
    'Three Billboards Outside Ebbing, Missouri', 
    'Moonlight', 
    'The Post', 
    'Lady Bird', 
    'The Dark Knight Rises',
    'The Curious Case of Benjamin Button', 
    'Silver Linings Playbook', 
    'The Bourne Identity', 
    'Skyfall', 
    'Mission: Impossible - Fallout',
    'Inglourious Basterds',
    'The Truman Show',
    'Shutter Island',
    'The Pianist',
    'The Departed',
    'Titanic',
    'The Avengers',
    'Guardians of the Galaxy',
    'Iron Man',
    'Avatar',
    'Jurassic Park',
    'Braveheart',
    'Die Hard',
    'The Sixth Sense',
    'Eternal Sunshine of the Spotless Mind',
    'The Social Network',
    'A Beautiful Mind',
    'Indiana Jones: Raiders of the Lost Ark',
    'Rocky',
    'Scarface',
    'The Godfather Part II',
    'The Good, the Bad and the Ugly',
    'American Beauty',
    'The Great Gatsby',
    'V for Vendetta',
    'The Incredibles',
    'Gladiator',
    'The Bourne Ultimatum',
    'Good Will Hunting',
    'Finding Nemo',
    'The Revenant',
    'The Hunger Games',
    'The Notebook',
    'Cast Away',
    '12 Years a Slave',
    'Slumdog Millionaire',
    'The Silence of the Lambs',
    'Deadpool',
    'Deadpool 2'
    'The Big Short',
    'The Green Mile',
    'Ford V Ferrari',
    'la la land',
    'Oppenheimer',
    '365 days',
    'creed',
    'creed ii',
    'creed iii',
    'the irishman'
]
